$ANSIBLE_VAULT;1.1;AES256
62646132386162393463316131333062333437393462303232653765326430303130326165393032
6433313264323465373435623061323831333865653633630a343330313661643136643666653830
66363865356231633438333733323832393333613430396336353234336435333630613461323839
3463633063306538360a373032343131383631363334393038643861353464386439656138323661
65303565646664643335653738623339323336656665656236643939376238653661376165363239
37373839656333623836626564616264333534346630323865666436353933376536643735373735
38636662656666396263383738306238636634376636383165363733643964636631346665356532
64653935656565646137346662336632323438353234353632643835303235653665336266646262
37643438626332363037376366393735343266663530313038376337333862623339383234383661
37666339353066643964656139316665626531353262376239653234383738383634393738653630
64623633353832663364353039643861333963326161326631656337633065326636333932343362
36346436613932653065653034363662393165633435353262653038323232656234643964333430
31303633303862346566653732646632633932353830376636656537633037346465613639373361
32343963383063323465613538346438666433323130613233663266383630373733326163303861
33356163303966313361616534333235633938323235333334306237316137613830343432303933
30643432656562346564626230393265356534626538663861623732343366663537376461333034
38643964653036343066643737356639353134393336653531343564306532653339663835396135
35386235633533353334326632383864303566303961373165393363376531663833313765386238
373637663139363539353062323031613836
