$ANSIBLE_VAULT;1.1;AES256
64653132336265326635396634313534666631633638663566643064396234393262356138323662
6363623533386134363439663531663139336334313631650a303262663530303062323134636639
66326366653832643264643362643262376561326534646264313964323866623034633137376530
3736316635323665620a663962386231306162613066623639363266633062396261643139613133
34396661336561613334643263383366316665386533306563666161616265633836333166626362
61373835636262663737616637383762623265373564616461613861343237333765626337383032
31373862393262656538363539336236313334633730366332363562626136393064663639383065
30333062613263383563373839613639346564303634663162393938653865366435363665393536
35636137323262646133646437653436613964653565303836643837316236653631393230646238
35393062623766356332616135616631313530646238363133326231373135633234343262366133
34346136336431363930313065663033333135386634343338306662633935326136376534646562
35373935333139366561326566623037633737323962376262643336326262616166303362346564
30366363366265623437653538383063346666636437616263643634396330346432636662363531
64643135316261353366323161653433303837383134613661663931363562656364623632396333
63663934303536646165356164646434386361653362393561363732366162356666616332363931
33656463376235646163333638643137376530343333633138653865366366626637323164323061
38343765636130633337343637363332363735653433633330383362643138626635323465613732
66616363373665346130343434393365376539623062623737323736656162353237623233313534
623962636661303963306236303366653862
