$ANSIBLE_VAULT;1.1;AES256
38636632376437666533376366646238333536373037663437393239653964343262333630646637
6531623064363561333831366637623766643466303330300a653130373639306435633938626333
38623337306566643938346436316363343362363135386631613166623166353832353939663031
6236633536373036630a326531396137353064313661626133373738343232663939386262386564
30326231613362343264356139653232356166313831663639613039366566613934356263663564
36333539303139623961383434316532303665636335396233613633633232316134623130393938
38336231643831633462326434326266663038656566343865623434393565646633623730633036
38386233376433643164363132376131336439323031386337346336663066666461626562356239
31653139666634666538633533306234633432643833343632343433656538343137343731306134
38633038363633616465373763656434303834653664396135316537626630326565383937333837
32613632313863623166353431313461656665373633333530633834343036343766633062356437
63626565613064373664333031316437353130613235626633623430623435323538313035333230
63326461376333643663313537363037353638396436356465613861393337343466363431353863
64386236353461396664353236313664373664663866636265353233616233653531303364353033
62376466613164356632333735626339303062306664306463623736653738383366366431336635
65366238656233633434613466633838623738313637656535653238646164303564323831386638
36366539306638623335633832343862623536336238346638386462353431656666383066383066
34393462613164323665373337643862653931396139323339316137393538663966626437653839
616635353537636237323761376136366136
