$ANSIBLE_VAULT;1.1;AES256
35343032363864343365383431383465626362363433666433636430343131643664313832336637
3632666665343636376362306463633430376138623534320a333034356232646538636264306632
61663731626234616332336563323135383466333135666536343138333337613233313135353339
3661356239656262390a373961376534633231376133633763343462346337656661343663613239
34376433623730633664356331323435616530366539303361316163356632653734336539373636
30656435316236336233323664343733626139353836653363656435663363346436363766386337
32636136343262333433663039643364623530383838396436386539643166663230363063346536
34623565343261386263363432353838653638303833383634303238666533376633376266393766
32313366623536386436346431383538393561326164633035336265383230353830623330323131
6332613831303962363864313731376361316330653636626164
