$ANSIBLE_VAULT;1.1;AES256
31633632646562633339346166383938386138336363636133643538623236376539306238373963
6636643036353636383630666561303463666535393462380a633631636137376266346464376639
32376136316638356665653735623030653336323635613062366632386338393031663231663664
6463656561353961610a353766326330396565316364303066653739353163386161386439306535
36623836333064386138333330303534633733366565643635666461643430616334666461303339
36613363653537363961386663363736643561663566303439663065343333356235313735313135
66386261626364396364613039616635386462623762636137613031363036646230656432326463
37666234633637643231373363323064343461653966363065626235666162346630643736366162
63666533376634613462653965346539373437346266643438616166383538646632386433663434
3038643930383637326135623564343062363865643238663433
