apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ./flux-system
  - ./infrastructure/namespaces
  - ./monitoring/grafana
  - ./monitoring/prometheus
  - ./monitoring/kube-state-metrics
  - ./monitoring/node-exporter
  - ./monitoring/alertmanager
  - ./services/homepage
  - ./services/jellyfin