apiVersion: v1
kind: Secret
metadata:
    name: grafana-admin
    namespace: monitoring
type: Opaque
stringData:
    admin-password: ENC[AES256_GCM,data:VnuVGrCk,iv:rhlUYsXMkg2RdLarqr3VLusPqAXW8q3day8MrJ90478=,tag:cQ35wrhayOcfECRGA1z1CA==,type:str]
sops:
    age:
        - recipient: age1t35sxk7cxkxk0rgfdmnkcnvky7zuf7g9407d3s03qyggu3w62adqnst5ya
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBCNWd1MWRncTNZekNYV2VF
            MWQyckJyNFR5YkZPQ2dDTGk3RVZDQm5oa0h3CmRtSHIwaExtQVFzWHlXYTFMeUdi
            d2ZnRUlFSUpXa3dNM0lxUGl6cGhFZkkKLS0tIGszVWQvTEhHZHdESGdsUEdJQWZ4
            TlRJVHhjckNsSXR4Z1cvNmdUN1B6NlUKof+0dGyo6Zc5EvniJzowAc94v3CCviYD
            33cwb6JhAYpfbaW93NdKu283tVGvES4riwExkZ34Fwhw5D+rIn1V3g==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-01-30T16:01:57Z"
    mac: ENC[AES256_GCM,data:G8I+X//lSJ5s4WxA4NTQY+GMxD1avfiXWHnQfnETw+r6ofaUgotufQkj+X5gkg+0sRwsNnyCPs6ozxfuiCW980YdTBUz2WVDrms0dp9COfJyQfwe/cYCoVglGU/FFaf3dkC6reVlLACzbih/sDF41WVzt/uvL2FrsY3jmeRxBJ0=,iv:NJzFelY2e99unVVY2apaRhhl2RP3WqwdCDmXZs4NjKA=,tag:+iGDun37KdZTXIDWEI9gTw==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.11.0
