apiVersion: ENC[AES256_GCM,data:0S8=,iv:ExGgi5KOEily/euvAxtodECAe36yzlBkkR2WfKGFL2o=,tag:FHU6jGOSikIz2sR3o8H+lw==,type:str]
kind: ENC[AES256_GCM,data:RpsHm71Z,iv:IleWc+Z43EyeHVN49ou6u0AyXo5/bXosZyk1HZPYLRY=,tag:m6EtXXUsIrl5kqXGj2gEXw==,type:str]
metadata:
    name: ENC[AES256_GCM,data:wNdxfkhxvgL3J2aVkA==,iv:lvcQzAj35QqnqdUKnIyGSvdBv9MXjqI8svju+sGbOVI=,tag:PqROwDmLKgFbVV8KorSMXA==,type:str]
    namespace: ENC[AES256_GCM,data:yIhHXuDC3S1pdg==,iv:Y+ZQREfqusL38Vi7jyv8M47/guV2PafTOtVJzaiOvcI=,tag:FaO0d2yHwWsXs2aT9hXD/A==,type:str]
type: ENC[AES256_GCM,data:s+BXc2sU,iv:nCgpBidLG2DO0w6CdS8Amy9SNA7R6GchDCOvyyOrGPY=,tag:Ud/gAVRKwDcLzwS4JWYjCg==,type:str]
stringData:
    admin-password: ENC[AES256_GCM,data:oCf3Y8/L,iv:Rcea3BjMiX6C4w8912S4EBJRMqE4QWpYIP1g6hnr3MA=,tag:fiy6hik2mB6erpRHpjO0hg==,type:str]
sops:
    age:
        - recipient: age1t35sxk7cxkxk0rgfdmnkcnvky7zuf7g9407d3s03qyggu3w62adqnst5ya
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBMbHlzSG5UTXE5TlN4b2Ni
            Nlk2MCt1YWluZjNHVnBOT3FvR0paVHRqa0Y0CkxzUmM2YytXUEtyaUdjcHlTcTZx
            b3IrV3F2U0N0d2pEMXMwMEd6UlY5T3cKLS0tIEEycDBIS2JPaExHRG10T0haK3hr
            VXdwVFlGcTNkV1hBelV2MG93WGtiWXcKr8k7Cok/rj6CoPpOHyLw3DjnKYRJvALG
            QsWtDfF4spd7B/hCaSgGADYPV4F7FEqHnBdKoK/Aqek/6M8N6bVfBw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-01-30T14:46:06Z"
    mac: ENC[AES256_GCM,data:h6q1qd9bmNdYfnntaD33kLG4ofLRaOgO1qjFigS2D0eRWqhD/HDgmol5ox0e6jrMdVPRkSNxhjEb27WcG/F/pXMfm60D84tVCoYmHRd0MykAJO9kkswwwjCffFc1TBQnIDnafMkyH0ov+csDpXTKHErRwFW/wVoNibokv39/Jhs=,iv:KyB+vZR43N+RA5vQkS5+7NDMqdfA2sS2aqtMhMW+xm8=,tag:neoBRmDwbEQ7U8gKTpArOw==,type:str]
    unencrypted_suffix: _unencrypted
    version: 3.11.0
