- name: Install K3s Server
  ansible.builtin.shell: >
    curl -sfL https://get.k3s.io | 
    INSTALL_K3S_EXEC='--flannel-backend=none --disable-network-policy --disable=traefik --disable=servicelb' 
    sh -s - server --write-kubeconfig-mode 644
  args:
    creates: /usr/local/bin/k3s

- name: Wait for Node Token to be generated
  ansible.builtin.wait_for:
    path: /var/lib/rancher/k3s/server/node-token

- name: Read Node Token
  ansible.builtin.slurp:
    src: /var/lib/rancher/k3s/server/node-token
  register: node_token_encoded

- name: Store Token as a dummy host variable
  ansible.builtin.set_fact:
    k3s_token: "{{ node_token_encoded['content'] | b64decode | trim }}"

- name: Fetch Kubeconfig to Legion
  ansible.builtin.fetch:
    src: /etc/rancher/k3s/k3s.yaml
    dest: ../../../k3s-homelab.yaml
    flat: yes

- name: Update Server IP in local Kubeconfig
  delegate_to: localhost
  become: false
  ansible.builtin.replace:
    path: ../../../k3s-homelab.yaml
    regexp: '127.0.0.1'
    replace: "{{ hostvars['k3s-node-0']['ansible_host'] }}"

- name: Download and install Helm
  ansible.builtin.shell: |
    curl https://raw.githubusercontent.com/helm/helm/main/scripts/get-helm-3 | bash
  args:
    creates: /usr/local/bin/helm

- name: Add Cilium Helm repository
  kubernetes.core.helm_repository:
    name: cilium
    repo_url: https://helm.cilium.io/
  environment:
    KUBECONFIG: /etc/rancher/k3s/k3s.yaml

- name: Install Cilium CNI via Helm
  kubernetes.core.helm:
    name: cilium
    chart_ref: cilium/cilium
    chart_version: "1.15.1"
    release_namespace: kube-system
    create_namespace: false
    values:
      k8sServiceHost: "{{ ansible_default_ipv4.address }}"
      k8sServicePort: 6443
      kubeProxyReplacement: strict
      operator:
        replicas: 1
      ipam:
        mode: kubernetes
      ingressController:
        enabled: true
        loadbalancerMode: shared
        default: true
      l2announcements:
        enabled: true
      externalIPs:
        enabled: true
  environment:
    KUBECONFIG: /etc/rancher/k3s/k3s.yaml