apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ../../base/homepage
# patches:
#   - patch: |-
#       - op: replace
#         path: /spec/template/spec/containers/0/env/0/value
#         value: 192.168.0.109:3100
#     target:
#       kind: Deployment
#       name: homepage