- name: Fedora 43 KDE Server Setup
  hosts: fedora
  become: true

  vars_prompt:
  - name: target_hostname
    prompt: "Enter hostname"
    default: "fedora"
    private: false

  roles:
    - hostname # Only run once
    - update
    - virtualization
    - tailscale
    - nginx
    - flush-nft # Temp solution, final firewall config is needed
